services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - postgres
    networks:
      - network
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres_db:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d:ro
    env_file:
      - .env
    networks:
      - network

volumes:
  postgres_db:
    driver: local

networks:
  network:
    driver: bridge
